#!/usr/bin/ruby

### Run the boostrap

if ARGV.length < 1 then
  puts "Please, use hizilla -h."
  exit
end

if ARGV[0] == "test" then
  puts "Running test commands..."
  system("./Hifile")
elsif ARGV[0] == "bootstrap"
  puts "Copying bootstrap files..."
  puts "Copying default Hifile..."
  system("cp /home/afm/khalin/conf/Hifile Hifile")
  puts "Hifile copied correctly!"
  puts "Bootstrap ended."
elsif ARGV[0] == "instance"
  puts "Randomizing instance name..."
  iname = rand(1 + 1000)
  if File.directory? '/home/afm/kensaku/hizilla-v01-t' + iname.to_s then
    puts "Randomized name already exists. Try it again..."
  else
    puts "Randomized instance name " + iname.to_s + ". Creating directory..."
    system("mkdir /home/afm/kensaku/hizilla-v01-t" + iname.to_s)
    puts "Instance created correctly!"
  end
else
  puts "Commands for Hizilla: "
  puts "hizilla bootstrap\tCreates a default Hifile and other config files."
  puts "hizilla test\tRuns the test specified in the Hifile."
  puts "hizilla instance\tCreates a new insteance inside the ~/kensaku directory."
end
